plugins {
    id 'java-library'
}

group = 'de.rsev.utilities'
version = '2.0.0'

sourceSets {
    main.java.srcDirs = ['.']
    main.java.exclude('build/**', 'out/**', 'gradle/**')
}

repositories {
    mavenCentral()
}

dependencies {
    // no external dependencies by design
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
